<a href="https://colab.research.google.com/github/mhdfudhail/Transfer_learning_of_Tensorflow_lite/blob/main/Transfer_learning_TFLite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tflite_runtime.interpreter import Interpreter 
from PIL import Image
import numpy as np
import time

data_folder = "/home/pi/TFLite_MobileNet/"

model_path ="/content/drive/MyDrive/Colab Notebooks/detect (1).tflite"
label_path = "/content/drive/MyDrive/Colab Notebooks/label.txt"

interpreter = Interpreter(model_path)
print("Model Loaded Successfully.")

interpreter.allocate_tensors()
_, height, width, _ = interpreter.get_input_details()[0]['shape']
print("Image Shape (", width, ",", height, ")")

# Load an image to be classified.
image = Image.open("/content/drive/MyDrive/Colab Notebooks/waste.jpg").convert('RGB').resize((width, height))

# Classify the image.
time1 = time.time() 
label_id, prob = classify_image(interpreter, image)
time2 = time.time()
classification_time = np.round(time2-time1, 3)
print("Classificaiton Time =", classification_time, "seconds.")

# Read class labels.
labels = tf.load_labels(label_path)

# Return the classification label of the image.
classification_label = labels[label_id]
print("Image Label is :", classification_label, ", with Accuracy :", np.round(prob*100, 2), "%.")

In [8]:
import tensorflow as tf
from PIL import Image
import numpy as np
import time

In [9]:
interpreter = tf.lite.Interpreter("/content/drive/MyDrive/Colab Notebooks/detect (1).tflite")
print("Model Loaded Successfully.")

Model Loaded Successfully.


In [10]:
interpreter.allocate_tensors()
_, height, width, _ = interpreter.get_input_details()[0]['shape']
print("Image Shape (", width, ",", height, ")")

Image Shape ( 300 , 300 )


In [46]:
image = Image.open("/content/drive/MyDrive/Colab Notebooks/3.jpg").convert('RGB').resize((width, height))
# print("image loaded",image.shape())

In [47]:
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [48]:
#Preprocess the image to required size and cast
input_shape = input_details[0]['shape']
input_tensor= np.array(np.expand_dims(image,0))

In [49]:
#set the tensor to point to the input data to be inferred
input_index = interpreter.get_input_details()[0]["index"]
interpreter.set_tensor(input_index, input_tensor)

In [50]:
#Run the inference
interpreter.invoke()
output_details = interpreter.get_output_details()

In [51]:
print(output_details)

[{'name': 'TFLite_Detection_PostProcess', 'index': 252, 'shape': array([ 1, 10,  4], dtype=int32), 'shape_signature': array([ 1, 10,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'TFLite_Detection_PostProcess:1', 'index': 253, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'TFLite_Detection_PostProcess:2', 'index': 254, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32)

In [52]:
output_data = interpreter.get_tensor(output_details[0]['index'])
# print(output_data)
results = np.squeeze(output_data)
# print(results)
top_k = results.argsort()
print(top_k[1])
final = top_k[1]
final = final[0]
print(final)
outputList =  ["paper","plastic","waste"]
print(outputList[final])

[0 1 3 2]
0
paper


In [1]:
import tensorflow as tf
from PIL import Image
import numpy as np
import time

In [16]:
interpreter = tf.lite.Interpreter("/content/drive/MyDrive/Colab Notebooks/detect (1).tflite")
# interpreter = tf.lite.Interpreter("/content/drive/MyDrive/Colab Notebooks/twoclassModel.tflite")
print("Model Loaded Successfully.")

Model Loaded Successfully.


In [17]:
interpreter.allocate_tensors()
_, height, width, _ = interpreter.get_input_details()[0]['shape']
print("Image Shape (", width, ",", height, ")")

Image Shape ( 300 , 300 )


In [22]:
# image = Image.open("/content/drive/MyDrive/Colab Notebooks/1.jpg")
# image.show()

# image = Image.open("/content/drive/MyDrive/Colab Notebooks/4.jpg").convert('RGB').resize((width, height))
# print("image loaded")
# input_details = interpreter.get_input_details()
# output_details = interpreter.get_output_details()
# #Preprocess the image to required size and cast
# input_shape = input_details[0]['shape']
# input_tensor= np.array(np.expand_dims(image,0),dtype = np.float32)
# #set the tensor to point to the input data to be inferred
# input_index = interpreter.get_input_details()[0]["index"]
# interpreter.set_tensor(input_index, input_tensor)
# #Run the inference
# interpreter.invoke()
# output_details = interpreter.get_output_details()
# print(output_details)
# output_data = interpreter.get_tensor(output_details[0]['index'])
# print(output_data)
# results = np.squeeze(output_data)
# print(results)
# top_k = results.argsort()
# print(top_k)
# print(top_k[1])

# final = top_k[1]
# final = final[2]
# print(final)
# outputList =  ["paper","plastic","metal"]
# print(outputList[final])


fileList = ["1.jpg","2.jpg","3.jpg","4.jpg","5.jpg","6.jpg","7.jpg","8.jpg","9.jpg","10.jpg","11.jpg","12.jpg"]
for i in fileList:
  image = Image.open("/content/drive/MyDrive/Colab Notebooks/"+i).convert('RGB').resize((width, height))
  # print("image loaded" + " = " + i)
  input_details = interpreter.get_input_details()
  output_details = interpreter.get_output_details()
  #Preprocess the image to required size and cast
  input_shape = input_details[0]['shape']
  input_tensor= np.array(np.expand_dims(image,0))
  # input_tensor= np.array(np.expand_dims(image,0),dtype = np.float32)
  #set the tensor to point to the input data to be inferred
  input_index = interpreter.get_input_details()[0]["index"]
  interpreter.set_tensor(input_index, input_tensor)
  #Run the inference
  interpreter.invoke()
  output_details = interpreter.get_output_details()
  print(output_details)
  output_data = interpreter.get_tensor(output_details[0]['index'])
  # print(output_data)
  results = np.squeeze(output_data)
  # print(results)
  top_k = results.argsort()
  # print(top_k)
  print("image loaded" + " = " + i) 
  print(top_k[1])
  final = top_k[1]
  final = final[2]
  print(final)
  outputList =  [0,"paper","plastic","metal"]
  print(outputList[final])


[{'name': 'TFLite_Detection_PostProcess', 'index': 252, 'shape': array([ 1, 10,  4], dtype=int32), 'shape_signature': array([ 1, 10,  4], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'TFLite_Detection_PostProcess:1', 'index': 253, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'TFLite_Detection_PostProcess:2', 'index': 254, 'shape': array([ 1, 10], dtype=int32), 'shape_signature': array([ 1, 10], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32)

In [ ]:
[0 2 1 3] = 1 = paper
[0 1 3 2] = 2 = pen
[0 2 1 3] = 3 = plastic
[0 2 1 3] = 4 = plastic
[1 0 3 2] = 5 = paper
[0 1 2 3] = 6 = pen

7 = plastic
8 =
9 =
10 =
11 = 
12 =